/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 scene.gltf --transform 
Files: scene.gltf [5.77KB] > C:\Users\ghapzh\Desktop\r3f\public\models\explosion\scene-transformed.glb [12.76KB] (-121%)
Author: Scientist Broken 🤓👆 (https://sketchfab.com/ultra700cybercam)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/explosion-1947033ff2d34875a7a88502a54d265a
Title: explosion
*/
/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
import { useGLTF } from '@react-three/drei'

export function Explosion(props) {
  const { nodes, materials } = useGLTF('./models/explosion/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_8.geometry} material={materials.GetHeroes_Add} rotation={[Math.PI, 0, Math.PI]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('./models/explosion/scene-transformed.glb')
