/* eslint-disable no-unused-vars */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 scene.gltf --transform 
Files: scene.gltf [37.89KB] > C:\Users\ghapzh\Desktop\r3f\public\models\various_planets\scene-transformed.glb [15.74MB] (-41434%)
Author: feivelyn (https://sketchfab.com/feivelyn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/various-planets-73c6c24e7c40409cafc6adacd5d71ff5
Title: Various Planets
*/
/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */


import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'


export function Planets(props) {
  const group = useRef()
  const planet1 = useRef()
  const planet2 = useRef()
  const planet3 = useRef()
  const planet4 = useRef()
  const planet5 = useRef()
  const planet6 = useRef()
  const planet7 = useRef()
  const planet8 = useRef()
  const { nodes, materials, animations } = useGLTF('./models/various_planets/scene-transformed.glb')
  
  const { actions } = useAnimations(animations, group)

  
  useFrame(() => {
    planet1.current.rotation.x += 0.01
    planet2.current.rotation.y += 0.05
    planet3.current.rotation.y += 0.05
    planet4.current.rotation.y += 0.007
    planet6.current.rotation.x += 0.0007
    planet6.current.rotation.y += Math.PI / 2
    planet7.current.rotation.y += 0.02
    planet7.current.rotation.z += 0.02
    planet8.current.rotation.y += 0.05
  })
  
  
  return (
    <group  ref={group} {...props} dispose={null}>
      <group  name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode">
          <group ref={planet1}  position={[-15, 10, -20]} name="planet_smac_0">
            <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.Planet_smac} />
          </group>
          <group ref={planet2} name="planet_gas_2" position={[23, 2, -24]}>
            <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Planet_gas} />
          </group>
          <group ref={planet3} name="planet_gas_cloud_01_3" position={[-3, -25, -80]} scale={0.962}>
            <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.planet_gas_cloud_01} />
          </group>
          <group ref={planet4} name="planet_continental_4" position={[4, 2, 70]}>
            <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.Planet_continental} />
          </group>
          <group ref={planet5} name="planet_continental_clouds_5" position={[-15, -20, 20]} scale={0.968}>
            <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.planet_continental_cloud} />
          </group>
          <group ref={planet6} name="planet_frozen_6" position={[3, 0, -65]}>
            <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.Planet_frozen} />
          </group>
          <group ref={planet7} name="planet_lava_7" position={[-8, 0, -34]}>
            <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.Planet_lava} />
          </group>
          <group ref={planet8} name="planet_barren_8" position={[1, 6, 50]}>
            <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.Planet_barren} />
          </group>
          {/* <group ref={planet} name="planet_gas_cloud_02_9" position={[0, 0, -3]} scale={0.973}>
            <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.planet_gas_cloud_02} />
          </group> */}
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/various_planets/scene-transformed.glb')
