/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 scene.gltf 
Author: myf565351409 (https://sketchfab.com/myf565351409)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rocket-2e6013515df6419598cf9f0d384a5b79
Title: rocket
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Satelite(props) {
  const { nodes, materials } = useGLTF('./models/satelite/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_9.geometry} material={materials['.001']} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.material} />
    </group>
  )
}

useGLTF.preload('./models/satelite/scene.gltf')
